### ISSUE TITLE
Requestly stop working fine on some links

### ISSUE THREAD

**Issue by Harfho** [requestly/customer-support#104]
when I first wrote this rule it works fine, but now it has stop working.
I what it to  Modify Response Headers Rule and remove Location from the Response Header.
also there is another Cancel Request Rule that stop working. 

cancel request that's not working -  https://www.awesomescreenshot.com/image/6909178?key=46941f245fe0f6a621c89d1ff3f9b754

modify Response that's not working - https://www.awesomescreenshot.com/image/6909386?key=3f7c9d848449a46a31dabd42c474656c

**Comment by requestly-team** [comment]
Hey @Harfho 

Thank you so much for reaching out. Can you please share the rule with us so that we can import the rule and try on our end. You can share the rules with us by creating a SharedList - https://docs.requestly.io/managing-rules/sharing

Also, provide us the URL on which you are trying the Cancel Rule.

Please provide the same information for the Headers rule too
1. Rule (by Sharing)
2. URL on which you want the modification to happen

**Comment by Harfho** [comment]
https://app.requestly.io/rules/#sharedList/1617197035339-share

https://topcryptoz.net/?link=UvEyH
http://megafly.in/bm1gKS8K - this will work, but will not work when visit from another website , it will just be immediately redirect.
