### ISSUE TITLE
Not adding a simple HTTP header 

### ISSUE THREAD

**Issue by lightningnetworkstores** [requestly/customer-support#118]
HTTP header not being added. What am I doing wrong?

![image](https://user-images.githubusercontent.com/36745356/121254505-3dadf580-c8a2-11eb-9f94-9a088c589fe3.png)

![image](https://user-images.githubusercontent.com/36745356/121254567-51595c00-c8a2-11eb-9013-c7d6da31abd4.png)

![image](https://user-images.githubusercontent.com/36745356/121254747-88c80880-c8a2-11eb-9087-2bd05873c07a.png)

![image](https://user-images.githubusercontent.com/36745356/121254781-941b3400-c8a2-11eb-8f68-07241c434e31.png)

**Comment by requestly-team** [comment]
Hey @lightningnetworkstores Thanks for logging the issue. We just tried to reproduce the issue at our end and it worked perfectly. Here is a screenshot of the Chrome Developer Tools

![image](https://user-images.githubusercontent.com/35186614/121291699-551eca00-c906-11eb-9b6e-79c51ff4f26a.png)

Here's a screenshot of Modify Headers Requestly Rule

![image](https://user-images.githubusercontent.com/35186614/121291716-62d44f80-c906-11eb-887d-e5227c2ee798.png)

## For the next steps, Can we please check the following

### Check Permissions you have given to Requestly Chrome Extension
Open this - `chrome://extensions/?id=mdnleldcmiljblolnjhpnblkcekpdkpa` in your Chrome Address Bar and check if you have given permissions to all Urls

![image](https://user-images.githubusercontent.com/35186614/121292080-fdcd2980-c906-11eb-91de-1c23f85ab88f.png)

### Check Extension Status

Can you please do a right click on extension status and check if the extension is activated or not. It is possible you might have deactivated Requestly earlier and forgot to activate it again

Just do a right click and then click on `Activate Requestly`
![image](https://user-images.githubusercontent.com/35186614/121292235-3ec53e00-c907-11eb-9608-f3fea54b3bce.png)

Please let us know if this helps! Otherwise we can come on a quick call and help you out.

**Comment by lightningnetworkstores** [comment]
Thanks, the issue was solved by right-clicking and activating it.
