### ISSUE TITLE
Uploading Rules - Quota Exceeded (QUOTA_BYTES_PER_ITEM)

### ISSUE THREAD

**Issue by joshuatz** [requestly/customer-support#23]
Most people probably don't run into this, but I noticed that when trying to upload a rather large rule export file, the rules page will toast "All rules imported successfully" and show that the rule has been uploaded, but if you refresh the page, it disappears from the list. Upon further inspection, it looks like the quota limits for Chrome's Storage API is getting exceeded.

Attached is a file that you can use to replicate this - [requestly_test_json.txt](https://github.com/requestly/requestly-issues/files/1584477/requestly_test_json.txt)

And here is a quick visual demo: 
![requestly_quota_exceeded](https://user-images.githubusercontent.com/17817563/34323068-a694f218-e7ed-11e7-8c76-1f1eeebd8637.gif)

After a  quick peek at background.js it seems like the extension tries to store everything in the "sync" storage area instead of local, correct? If so, a quick fix might be checking the byte size of the transformed contents of the file after upload, and if it exceeds the sync storage quotas, put it in local storage instead and mark some kind of internal flag. 

The quotas for local storage are enormous compared to sync, and if you add a special permissions flag to your manifest, it can actually be unlimited. Sync, on the other hand, is limited to a measly 8,192 bytes per item. - [Link](https://developer.chrome.com/apps/storage)

As a total sidenote - is there still a public git repo for this extension that is up to date? I see one marked "stale" and I have found some old forks, but I can't seem to find any that are up to date.

**Comment by sachinjain024** [comment]
Thanks @joshuatz. We are already aware about this issue/limitation. We did not work much in this direction considering this as very highly unlikely scenario. 

You are right about storage limits of local vs sync and we have chosen sync deliberately because it allows users to work on multiple computers.

I checked your test file and It contains a lot of duplicate entries. Maybe you created these entries only for test purpose but this is very rare for common users of requestly.

Given that, you need this to be solved. I would like to solve it in the following manner:
1. Show amount of space left in current storage system
2. User should be able to create rules in both storage systems
3. Show accordion in left rail (Local + Sync) as two options under Rules tab
4. When user uploads a file and we get an error due to size limit, handle that error gracefully and show proper error message to use local rule because it has more space left.

How urgently you want this to be solved ?

PS: We had requestly's source code open until recently we moved it to private repo.

**Comment by joshuatz** [comment]
Thanks for the response @sachinjain024 .

I totally agree about this being a very rare occurrence. I have been using Requestly at work for months and only ran into this limit a few times when trying to import a "blacklist" of domains and web assets to block for some very specific testing. The file I shared is indeed a dummy test file I generated, since I didn't want to have to redact information from that file I was using at work.

 I think your proposed solution is excellent - allowing graceful fallback from sync to local would certainly solve it. You could even hide the "local" tab in the accordion if the user has not yet used it  - since many users would likely never do so and it could potentially be unnecessarily confusing for them.

This is not at all urgent - I actually no longer need to overcome the limitation for work, since I found ways to break my export into smaller chunks for the testing I needed.

**Comment by requestly-team** [comment]
Hey @joshuatz We know we are very very late on responding on this ticket but we actually implemented a feature a couple of years ago which allows users to change the storage type.

Users can go to - https://app.requestly.io/settings and select their preferred storage type. Here is the screenshot-

![image](https://user-images.githubusercontent.com/35186614/108805263-b88a2380-75c5-11eb-93cd-5b13034465c6.png)

Just wondering if you are still using Requestly ?

**Comment by joshuatz** [comment]
@requestly-team No, I haven't used Requestly for a while now - not because of any dissatisfaction, but just haven't had a need for it lately. But, that looks like a great feature and would certainly addresses the issue I was having when I opened this - thanks for alerting me. I'll go ahead and close this out.

**Comment by requestly-team** [comment]
Thanks @joshuatz for the response & closing this ticket.
