### ISSUE TITLE
[FR] use offline options page

### ISSUE THREAD

**Issue by Cologler** [requestly/customer-support#38]
Currently:

`https://app.requestly.in/rules/` is the options page.

Expected:

`chrome-extension://?????/rules/` is the options page.

Reason:

* Faster.
* Open without internet.

**Comment by sachinjain024** [comment]
@Cologler Thanks for opening the issue. We have thought about this option and this is under road map. Instead of moving it under chrome-extension settings, we are thinking about using Service workers to provide offline capabilities. Not much work has been done yet, will let you know when we prioritize this.

**Comment by Cologler** [comment]
@sachinjain024 What happen if I try to create a rule which redirect (or cancel) `https://app.requestly.in/*` ?

**Comment by sachinjain024** [comment]
@Cologler You can try that. In our code, we have blacklisted **requestly.in** domain so none of your rules will ever apply to requestly.in domain + subdomains.
