### ISSUE TITLE
"Modify query parameters" is broken in Firefox

### ISSUE THREAD

**Issue by MrQubo** [requestly/customer-support#45]
I've tried to use requestly to disable new layout on youtube.
I'm using Firefox Quantum 61.0.2. Checked on Linux and Windows machine.
It works as expected in Chromium browser.

Steps to Reproduce:
- Add the "Modify query parameters" rule with `Host Equals www.youtube.com` and `disable_polymer=1` param.
- Try to visit [https://www.youtube.com](https://www.youtube.com).

Actual Behavior:
The page doesn't load. It seems like it loops infinitely.

Expected Behavior:
The `disable_polymer=1` parameter is added to the query.

Turning off the rule **after** visiting [https://www.youtube.com](https://www.youtube.com) yields the expected result.

**Comment by MrQubo** [comment]
Firefox crashes after I wait a minute or two waiting for the youtube homepage to load. It's repeatable.

**Comment by MrQubo** [comment]
Other websites work as expected.

**Comment by sachinjain024** [comment]
@MrQubo Thanks for logging the issue here. I have couple of questions here -

1. I tried to open youtube.com with disable_polymer=1 and without this parameter. I could not see any difference between the two pages. 
2. I tried to debug the issue but I could not reproduce it. I use MacOs

Secondly, If it is specific to youtube then it maybe youtube's behavior rather than requestly bug. If it is working on other websites, then it looks like youtube is preventing it to be opened with this parameter in firefox in Linux.

**Comment by MrQubo** [comment]
It's the new youtube layout. They're doing AB tests and it's being enabled for random people. But there's no option to turn it off except this query parameter. Here's the difference: [imgur.com/a/oSB9xYS](https://imgur.com/a/oSB9xYS).

I'll try to investigate it further.

**Comment by requestly-team** [comment]
Closing this ticket due to lack of response. Please reopen if you have any questions/concerns.
