### ISSUE TITLE
I get 307 response for preflight requests.

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [requestly/customer-support#48]
I want to redirect requests of my app to my mock server. Requests would be get, post, put, delete, etc. but I get `307 Internal Redirect` as response since the request would send out a preflight request.

**Comment by sachinjain024** [comment]
Hi @sprlwrksAprilmintacpineda Can you please share your rules with us (https://www.requestly.in/blog/2018/06/14/share-rules-with-other-users/) and we will gladly look into this issue. If you want to keep your rules private since this is a public repository, you can send us an email on `requestly.extension@gmail.com`

**Comment by xu20160924** [comment]
I face the same issue when I use Redirect URL to intercept API requests of browser from a remote server to my local server, I get 307 Internal Redirect too. Am I misusing it? Or cannot redirect API requests within the browser to my local server?
Another question is how to join Slack. I don't have an account matching these domains(anyclip.com
driven.cx). Am I need an invitation？
