### ISSUE TITLE
Requestly Replace rule: Regex group replace not working

### ISSUE THREAD

**Issue by gvmohzibat** [requestly/customer-support#95]
Based on [this link](https://www.requestly.in/blog/2018/06/16/replace-rule-documentation/), Regex group replacement is supported but it seems not.
I'm using this regex: `/^https:\/\/domain\.com\/serve\/(.+)\/myscript\.js$/gi`
and replace this: https://domain.com/serve/$1
with this: http://localhost:5980

But it's not working. When I change `$1` to the exact text, it works.

**Comment by requestly-team** [comment]
Hey @gvmohzibat Thanks for logging the issue. Can you please share the following with us

1. Share the Rule which you have created. Use SharedList feature to share the exact rule so we can directly import it - https://docs.requestly.io/managing-rules/sharing
2. What is the URL which you want to redirect
3. Destination of the URL

We understand there are certain variables which you would like to keep and hence using the Regex Operator So if you can share a couple of examples, It'd help us in providing a working rule to you.

**Comment by gvmohzibat** [comment]
Hi. Thanks for your quick response. I actually shared the items you mentioned in the last message. Here is [the SharedList link](https://app.requestly.io/rules/#sharedList/1614073476847-Debug-replace-rule)

**Comment by requestly-team** [comment]
Hey @gvmohzibat Thanks for providing the SharedList link! When we tried this at our end, it is working fine.

We tested this on the following URL - https://s1.mediaad.org/serve/tarafdari.com/homepage/loader.js and It took us to http://localhost:5980/homepage/loader.js which is expected.

Can you please share the following information?
1. What is the URL of your JS. We need to check whether the JS URL is matching the Regex or not properly. You can use this Regex - https://regex101.com/r/5W3lbE/1 to try out if your regex is working fine or not.
2. What is the URL of the website on which you are trying this?

Asking Question 2 above because you are trying to redirect a JS which is on HTTPs to a JS which is on HTTP so browser maybe blocking loading of your JS because of the mixed content.

**Comment by gvmohzibat** [comment]
I'm sorry it seems I've shared a wrong link (it doesn't have any regex group replacement). Check out [this screencast](https://app.usebubbles.com/2uF5v4qWrxn7zKrVnDNDSM/comments-on-regex101-com). I showed how to reproduce it and what I'm expecting.

About the questions:

1. `https://s1.mediaad.org/serve/tarafdari.com/loader.js`. [It's matching](https://regex101.com/r/aAkHwK/1) 
2. This is [an example link](https://www.tarafdari.com/node/1866544). about mixed content, the issue's that it's not redirected not that it's not loaded.

**Comment by requestly-team** [comment]
Oh I got the problem you are making! You cannot use the group value `$1` in the Replace part, it is supposed to be used in the destination part. 

Here is the documentation for understanding rule operators - https://docs.requestly.io/getting-started/rule-operators#regex-match-operator

Do you want to setup the following redirects

```
https://s1.mediaad.org/serve/tarafdari.com/loader.js --> localhost:5980/loader.js
```

If this is your use case, you can try this https://app.requestly.io/rules/#sharedList/1614304096123-Mediaad-Debug-Loader-Redirect-Rule

I set up a Redirect Rule here

URL `Matches Wildcard` `https://s1.mediaad.org/serve/*/loader.js`
Destination `http://localhost:5980/loader.js`

Please import the list above and let me know if it works.

**Comment by gvmohzibat** [comment]
@requestly-team Thanks a lot for your help. Great support!

**Comment by requestly-team** [comment]
Thanks @gvmohzibat -- Can you please rate us on Chrome Store https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
